// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/sent-messages": {
            "get": {
                "description": "Retrieves a list of all messages that have been sent.",
                "produces": [
                    "application/json"
                ],
                "summary": "List all sent messages.",
                "responses": {
                    "200": {
                        "description": "List of all sent messages are returned",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Message"
                            }
                        }
                    },
                    "500": {
                        "description": "Error message explaining the server error",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        },
        "/start-stop": {
            "post": {
                "description": "It enables you to start or stop the message sending according to \"action\" parameter.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "summary": "Start or stop the message sending.",
                "parameters": [
                    {
                        "description": "Action to start or stop",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.StartAndStopRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Message describing the status of the message sending service",
                        "schema": {
                            "$ref": "#/definitions/SuccessResponse"
                        }
                    },
                    "400": {
                        "description": "Error message explaining the invalid request payload or action",
                        "schema": {
                            "$ref": "#/definitions/ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.Message": {
            "type": "object",
            "properties": {
                "content": {
                    "description": "Size limit for message content",
                    "type": "string"
                },
                "to": {
                    "description": "Phone number must be in the form of +905xxxxxxxxx",
                    "type": "string"
                }
            }
        },
        "models.StartAndStopRequest": {
            "type": "object",
            "required": [
                "action"
            ],
            "properties": {
                "action": {
                    "description": "Action to be taken, either \"start\" or \"stop\"",
                    "type": "string",
                    "enum": [
                        "start",
                        "stop"
                    ]
                }
            }
        },
        "SuccessResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string",
                    "description": "Message describing the status of the message sending service"
                }
            }
        },
        "ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "description": "Error message explaining what went wrong"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{},
	Title:            "",
	Description:      "",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
