openapi: 3.0.1
info:
  title: API for Insider Case Study
  description: This is an automated message sending service API for Insider Case Study.
  contact:
    email: mkeremavci@gmail.com
  version: "1.0"
servers:
- url: http://localhost:${SERVER_PORT}
paths:
  /sent-messages:
    get:
      summary: List all sent messages.
      description: Retrieves a list of all messages that have been sent.
      responses:
        "200":
          description: List of all sent messages are returned
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/models.Message'
        "500":
          description: Error message explaining the server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  /start-stop:
    post:
      summary: Start or stop the message sending.
      description: It enables you to start or stop the message sending according to
        "action" parameter.
      requestBody:
        description: Action to start or stop
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/models.StartAndStopRequest'
        required: true
      responses:
        "200":
          description: Message describing the status of the message sending service
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        "400":
          description: Error message explaining the invalid request payload or action
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
      x-codegen-request-body-name: request
components:
  schemas:
    models.Message:
      type: object
      properties:
        content:
          type: string
          description: Size limit for message content
        to:
          type: string
          description: Phone number must be in the form of +905xxxxxxxxx
    models.StartAndStopRequest:
      required:
      - action
      type: object
      properties:
        action:
          type: string
          description: "Action to be taken, either \"start\" or \"stop\""
          enum:
          - start
          - stop
    SuccessResponse:
      type: object
      properties:
        message:
          type: string
          description: Message describing the status of the message sending service
    ErrorResponse:
      type: object
      properties:
        error:
          type: string
          description: Error message explaining what went wrong
x-original-swagger-version: "2.0"